config/routes.rb
Rails.application.routes.draw do
  devise_for :establishments
  devise_for :teachers
  devise_for :students

  root 'home#index'

  resources :students, only: [:show] do
    get '/dashboard', to: 'students#dashboard', as: 'dashboard'
  end

  resources :teachers, only: [:index, :show] do
    resources :establishments, only: [:index]
    resources :services, only: [:index]
    resources :teacher_cats, only: [:create, :destroy]
    get '/dashboard', to: 'teachers#dashboard', as: 'dashboard'
  end
  
  resources :establishments, only: [:index, :show] do
    resources :teachers, only: [:index]
    resources :services, only: [:index]
    get '/dashboard', to: 'establishments#dashboard', as: 'dashboard'

  end

  resources :resources, only: [:show, :create, :destroy, :edit] do
    resources :teachers, only: [:show]
  end

  resources :services, only: [:index, :create, :destroy] do
    resources :events, only: [:index, :create]
  end

  resources :events, only: [:show, :edit, :destroy]

end

app/models/service.rb
class Service < ApplicationRecord
  validates :name, presence: true
  validates :duration, presence: true
  validates :duration, numericality: { only_integer: true, greater_than_or_equal_to: 900, less_than_or_equal_to: 14400 }
  validate :resource_belongs_to_establishment
  validate :subcategory_belongs_to_teacher

  belongs_to :establishment
  belongs_to :teacher
  belongs_to :resource
  belongs_to :sub_category
  has_many :events

  private

  def resource_belongs_to_establishment
    unless self.establishment.resources.include?(self.resource)
      errors.add(:resource, "La ressource affiliée n'appartient pas à l'établissement affilié.")
    end
  end

  def subcategory_belongs_to_teacher
    unless self.teacher.sub_categories.include?(self.sub_category)
      errors.add(:sub_category, "La sous-catégorie n'est pas enseignée par ce professeur.")
    end
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @q = Service.ransack(params[:q])
    if params[:establishment_id]
      @establishment = Establishment.find(params[:establishment_id])
      @ransack = @establishment.services
    elsif params[:teacher_id]
      @teacher = Teacher.find(params[:teacher_id])
      @ransack = @teacher.services
    else
      @ransack = @q.result(distinct: true)
    end
    @establishments = Establishment.all
    @teachers = Teacher.all
  end

  def show
  end

  def create
    params[:service][:duration] = params[:service][:duration_minutes].to_i*60
    @service = Service.new(service_params)

    if @service.save
      flash[:success]="Le service a bien été créé !"
      redirect_back(fallback_location: root_path)
      return
    else
      flash[:danger]= @service.errors
      redirect_back(fallback_location: root_path)
      return
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    flash[:success]="Le service a bien été détruit !"
    redirect_back(fallback_location: root_path)
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def service_params
    params.require(:service).permit(:name, :description, :duration, :establishment_id, :teacher_id, :resource_id, :sub_category_id)
  end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/index.html.erb
<!-- TOP SLICE -->
<section class="slice slice-lg section-rotate">
    <div class="section-inner bg-gradient-info">
        <span class="section-inner-bg"></span>
    </div>

    <!-- main text -->
    <div class="container mt-xl">
        <div class="row align-items-center">
            <div class="col-lg-10 pl-0">
                <h1 class="text-white mb-3">Les Services</h1>
                <p class="lead text-white lh-180">Retrouvez ici tous les services disponibles sur AwaBooking !</p>

                <!-- search form -->
                <div class="row align-items-center pt-3">

                    <div class="col-6">
                        <%= search_form_for @q do |f| %>
                        <%= f.search_field :name_cont, class: "form-control", placeholder: "Trouver un service par type" %>
                    </div>

                    <div class="col-3">
                        <%= f.submit "Rechercher", class: "btn-sm btn-circle btn-info" %>
                    </div>
                    <% end %>

                    <% if @q.name_cont %>
                    <div class="col-3">
                        <%= link_to "Tous les services", services_path, class: "btn-sm btn-circle btn-danger" %>
                    </div>
                    <% end %>

                </div>

            </div>

        </div>
    </div>
</section>




<section class="slice-lg bg-transparent" id="top-index">
    <div class="container mt-5">
        <div class="row">

            <% @ransack.each do |service| %>

            <!-- cards -->
            <div class="col-lg-3 pt-5">
                <div class="card overflow-hidden" data-animate-hover="2" id="card-index">

                    <div class="card-body text-center">

                        <!-- name -->
                        <h5 class="card-title h6 mb-4">
                            <a href="<%= service_path(service) %>" class="text-dark">
                                <%=service.name%>
                            </a>
                        </h5>

                        <div class="mt-3">

                            <!-- duration -->
                            <p class="text-muted mb-2">
                                <i class="far fa-clock"></i>
                                <%=service.duration/60%> min </p>

                            <hr class="m-3">

                            <!-- teacher -->
                            <a href="<%=teacher_path(service.teacher)%>" class="text-muted mb-0">
                                <strong>Professeur</strong> <br>
                                <i class="fas fa-user-circle text-danger"></i> &nbsp;
                                <%=service.teacher.first_name%>
                                <%=service.teacher.last_name.upcase%>
                            </a>

                            <hr class="m-3">

                            <!-- establishment -->
                            <a href="<%=establishment_path(service.establishment)%>" class="text-muted mb-0">
                                <strong>Établissement</strong> <br>
                                <i class="fas fa-user-circle text-success"></i> &nbsp;
                                <%=service.establishment.name%> <br>
                            </a>

                            <!-- book appointment -->
                            <div class="pt-3">

                                <% if current_student %>
                                <a href="<%=service_events_path(service)%>" class="text-info">
                                   <strong> Réserver un créneau </strong> &nbsp; <i class="fas fa-angle-right"></i>
                                </a>
                                <% else %>
                                <a href="<%= student_session_path %>" class="text-info">
                                    <strong> Réserver un créneau </strong> &nbsp; <i class="fas fa-angle-right"></i>
                                </a>
                                <% end %>


                            </div>

                        </div>

                    </div>

                </div>
            </div>
            <% end %>

        </div>
    </div>
</section>