config/routes.rb
Rails.application.routes.draw do
  devise_for :establishments
  devise_for :teachers
  devise_for :students

  root 'home#index'

  resources :students, only: [:show] do
    get '/dashboard', to: 'students#dashboard', as: 'dashboard'
  end

  resources :teachers, only: [:index, :show] do
    resources :establishments, only: [:index]
    resources :services, only: [:index]
    resources :teacher_cats, only: [:create, :destroy]
    get '/dashboard', to: 'teachers#dashboard', as: 'dashboard'
  end
  
  resources :establishments, only: [:index, :show] do
    resources :teachers, only: [:index]
    resources :services, only: [:index]
    get '/dashboard', to: 'establishments#dashboard', as: 'dashboard'

  end

  resources :resources, only: [:show, :create, :destroy, :edit] do
    resources :teachers, only: [:show]
  end

  resources :services, only: [:index, :create, :destroy] do
    resources :events, only: [:index, :create]
  end

  resources :events, only: [:show, :edit, :destroy]

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :siret, presence: true
  validates :phone, presence: true

  has_and_belongs_to_many :sub_categories

  has_many :services, dependent: :destroy
  has_many :events, through: :services, dependent: :destroy
  has_many :establishments, -> { distinct }, through: :services
  has_one_attached :avatar
  
  after_create :welcome_send, :avatar_attach

  def upcoming_events
    events.order(start_time: :desc).select { |e| e.start_time > (DateTime.now- 1.week) }
  end


  def avatar_attach
    temp_user = self
    temp_user.avatar.attach(io: File.open("app/assets/images/neutral.jpeg"), filename: 'avatar')
  end

  
  def welcome_send
    ContactMailer.welcome_send(self).deliver_now
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
before_action :filter_on_signed_in, only: [:dashboard]
before_action :page_belongs_to_user?, only: [:dashboard]

  def show
    @teacher = Teacher.find(params[:id])
    @sub_categories = SubCategory.all.order(title: :asc)
    @sub_categories =  @sub_categories.select {|s| !@teacher.sub_categories.include?(s)}
  end

  def destroy
  end

  def dashboard
    @teacher = Teacher.find(params[:teacher_id])
    @events = @teacher.events
    
  end

  def index
    @q = Teacher.ransack(params[:q])
    @ransack = @q.result(distinct: true)
    if params[:establishment_id]
      @establishment = Establishment.find(params[:establishment_id])
      @teachers = @establishment.teachers
    else
      @teachers = Teacher.all
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/dashboard.html.erb
<!-- Main navbar -->
<nav class="navbar navbar-transparent navbar-light bg-light" style="height: 50px">
    <div class="container">
        <div class="row" style="display: flex; justify-content: space-between; width: 100%">
            <div style="padding-top: 5px;">
                <a href="<%= root_path %>">
                    <%= image_tag "AwaBooking.png", alt: "logo-row", class: "btn-translate--hover", style: "width: 130px; margin-left: 50px" %>
                </a>
            </div>
            <ul class="navbar-nav align-items-lg-center ml-lg-auto" style="margin-right: 40px">
                <li class="nav-item dropdown dropdown-animate " data-toggle="hover">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false"><i class="fas fa-user-circle align-items-center btn-translate--hover"
                            style="color: black; font-size: 1.5em"></i></a>
                    <div class="dropdown-menu dropdown-menu-md dropdown-menu-arrow" style="width: 170px">
                        <div class="list-group">
                            <a href="<%= teacher_path(current_teacher) %>" class="list-group-item list-group-item-action">
                                <div class="media d-flex align-items-center">
                                    <div class="media-body ml-3">
                                        <h6 class="mb-1">Profil</h6>
                                    </div>
                                </div>
                            </a>
                            <a href="<%= get_logout %>" class="list-group-item list-group-item-action" data-method="DELETE">
                                <div class="media d-flex align-items-center">
                                    <div class="media-body ml-3">
                                        <h6 class="mb-1"><strong>Déconnexion</strong></h6>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <%= render 'layouts/flash' %>

</nav>

<section class="slice bg-secondary" style="margin-top: -3.5em !important" id="dash">
    <div class="container-fluid">
        <!-- establishment name card -->
        <div class="row row-grid pr-3 ">
            <div class="col-3">

                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h5 class="heading h5 mb-0">
                                    <%= current_user.first_name %>
                                    <%= current_user.last_name %>
                                </h5>
                            </div>
                            <div class="col-4">
                                <div class="card-icon-actions text-right">
                                    <a href="<%=edit_teacher_registration_path%>" class="favorite active" data-toggle="tooltip"
                                        data-original-title="Save to favorites"><i class="fas fa-pen"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- floating menu -->
                <div data-toggle="sticky" data-sticky-offset="100">
                    <div class="card">
                        <div class="card-header border-0">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <h6 class="mb-0">Dashboard</h6>
                                </div>
                            </div>
                        </div>
                        <div class="list-group list-group-sm list-group-flush">
                            <a href="#rdv" class="list-group-item list-group-item-action d-flex align-items-center justify-content-between">
                                <div>
                                    <%= image_tag "img/icons/dusk/svg/numbered-list.svg", alt: "float menu icon", class: "avatar", style: "width: 33px" %>
                                </div>
                                <div class="flex-fill pl-3 text-limit">
                                    <h6 class="text-sm d-block text-limit">Mes rendez-vous (à venir)</h6>
                                </div>
                            </a>
                            <a href="#calendar" class="list-group-item list-group-item-action d-flex align-items-center justify-content-between">
                                <div>
                                    <%= image_tag "img/icons/dusk/svg/expired.svg", alt: "float menu icon", class: "avatar", style: "width: 33px" %>
                                </div>
                                <div class="flex-fill pl-3 text-limit">
                                    <h6 class="text-sm d-block">Mon Calendrier</h6>
                                </div>
                            </a>
                            <a href="<%=teacher_path(current_user)%>" class="list-group-item list-group-item-action d-flex align-items-center justify-content-between">
                                <div>
                                    <%= image_tag "img/icons/dusk/svg/maintenance.svg", alt: "float menu icon", class: "avatar", style: "width: 33px" %>
                                </div>
                                <div class="flex-fill pl-3 text-limit">
                                    <h6 class="text-sm d-block text-limit">Mon profil</h6>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-9">

                <!-- TABLE -->
                <div class="card" id="card-rdv">
                    <div class="card-header border-0">

                        <div class="d-flex justify-content-between align-items-center mb-2">
                            <div>
                                <h6>Mes rendez-vous</h6>
                            </div>
                            <div id="rdv" style="cursor:pointer;">
                                <i class="fas fa-angle-down"></i>
                            </div>
                        </div>

                        <% if current_user.upcoming_events.any? %>

                        <!-- resources list (table) -->
                        <div class="table-responsive container" id="hide-rdv">
                            <table class="table  table-flush align-items-center">
                                <thead class="thead-light">
                                    <tr class="row">
                                        <th class="col-2" style="color: rgba(0, 0, 0, 0.596)"> Date </th>
                                        <th class="col-2" style="color: rgba(0, 0, 0, 0.596)"> Heure </th>
                                        <th class="col-2" style="color: rgba(0, 0, 0, 0.596)"> Durée </th>
                                        <th class="col-5" style="color: rgba(0, 0, 0, 0.596)"> Description </th>
                                        <th class="col-1" style="color: rgba(0, 0, 0, 0.596)"><i class="fas fa-trash-alt"></i></th>
                                    </tr>
                                </thead>
                                <tbody class="container">
                                    <% current_user.upcoming_events.each do |event|%>
                                    <tr class="row">
                                        <td class="col-2" style="height: auto"><span class="font-weight-bold text-sm wrap">
                                                <%=(event.start_time).strftime("%d/%m/%Y")%></span></td>
                                        <td class="col-2" style="height: auto"><span class="font-weight-bold wrap">
                                                <%=Time.at(event.start_time).strftime("%Hh%M")%></span></td>
                                        <td class="col-2" style="height: auto"><span class="text-sm wrap">
                                                <%= Time.at(event.duration).utc.strftime("%Hh%M") %></span></td>
                                        <td class="col-5" style="height: auto"><span class="text-sm wrap">
                                                <%=event.name%></span></td>
                                        <td class="col-1" style="height: auto"><a href="<%= event_path(event) %>" class="text-light"
                                                data-toggle="tooltip" data-original-title="Remove item" data-method="DELETE"
                                                data-confirm="Vous allez supprimer l'évènement '<%=event.name%>'. Veuillez confirmer.">
                                                <i class="fas fa-trash-alt"></i></a></td>
                                    </tr>
                                    <%end%>
                                </tbody>
                            </table>
                        </div>

                        <% else %>

                        <div id="hide-rdv">

                            <div class="row mt-4 d-flex justify-content-around" id="hide-rdv">

                                <span class="mb-0">Aucun rendez-vous de prévu (pour le moment !)</span>

                            </div>
                        </div>

                        <% end %>



                    </div>

                </div>

                <!-- CALENDAR -->
                <div class="card mt-4" id="card-calendar">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center mb-2 justify-content-between">
                            <div>
                                <h6>Mon calendrier</h6>
                            </div>
                            <div id="calendar" style="cursor:pointer;">
                                <i class="fas fa-angle-down"></i>
                            </div>
                        </div>
                        <div id="hide-calendar">
                            <%= add_weekly_calendar(@events, nil, nil) %>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>
</section>

app/views/teachers/index.html.erb
<!-- TOP SLICE -->
<section class="slice slice-lg section-rotate">
    <div class="section-inner bg-gradient-info">
        <span class="section-inner-bg"></span>
    </div>

    <!-- main text -->
    <div class="container mt-xl">
        <div class="row align-items-center">
            <div class="col-lg-10 pl-0">
                <h1 class="text-white mb-3">Les Intervenants</h1>
                <p class="lead text-white lh-180">Retrouvez ici tous les intervants inscrits sur AwaBooking !</p>

                <!-- search form -->
                <div class="row align-items-center pt-3">

                    <!-- input field -->
                    <div class="col-6">
                        <%= search_form_for @q do |f| %>
                        <%= f.search_field :first_name_or_last_name_cont, class: "form-control", placeholder: "Trouver un intervenant par nom ou prénom" %>
                    </div>

                    <!-- research button -->
                    <div class="col-3">
                        <%= f.submit "Rechercher", class: "btn-sm btn-circle btn-info" %>
                    </div>
                    <% end %>

                    <!-- all teachers - shows only when research exists -->
                    <% if @q.first_name_or_last_name_cont %>
                    <div class="col-3">
                        <%= link_to "Tous les intervenants", teachers_path, class: "btn-sm btn-circle btn-danger" %>
                    </div>
                    <% end %>

                </div>
            </div>

        </div>
    </div>
</section>


<section class="slice-lg bg-transparent" id="top-index">
    <div class="container mt-5">
        <div class="row">

            <% @ransack.each do |teacher| %>

            <!-- cards -->
            <div class="col-lg-3 pt-5">
                <div class="card overflow-hidden" data-animate-hover="2" id="card-index">

                    <div class="overflow-hidden">
                        <div class="animate-this text-center">

                            <!-- avatar -->
                            <% if teacher.avatar.attached? %>
                            <%= image_tag teacher.avatar, class: "image-size" %>
                            <% else %>
                            <a href="<%= teacher_path(teacher) %>">
                                <%= image_tag ("prof2.jpg"), class: "image-size" %>
                            </a>
                            <%end%>

                        </div>
                    </div>

                    <div class="card-body text-center">

                        <!-- name -->
                        <h5 class="card-title mb-0"><a href="<%= teacher_path(teacher) %>" class="text-dark">
                                <%=teacher.first_name%>
                                <%= teacher.last_name %></a></h5>

                        <!-- services categories -->
                        <p class="text-muted mb-0">
                            <%teacher.sub_categories.each_with_index do |sub_cat, ind|%>
                            <%unless ind == 0 %>
                            -
                            <%end%>
                            <%=sub_cat.title%>
                            <%end%>
                        </p>

                        <!-- see profile -->
                        <div class="mt-3">
                            <a href="<%=teacher_path(teacher.id)%>" class="text-danger">
                                Voir le profil &nbsp; <i class="fas fa-user-circle"></i>
                            </a>

                            <!-- number of services availables -->
                            <hr class="m-2">

                            <!-- no service -->
                            <% if teacher.services.count == 0 %>
                            <a class="text-light">Pas de service disponible</a>

                            <!-- one service  -->
                            <% elsif teacher.services.count == 1 %>
                            <a href="<%=teacher_services_path(teacher.id)%>" class="text-info">
                                <strong> <%= teacher.services.count %> service disponible </strong> &nbsp; <i class="fas fa-angle-right"></i>
                            </a>

                            <!-- several services  -->
                            <% else %>
                            <a href="<%=teacher_services_path(teacher.id)%>" class="text-info">
                                <strong> <%= teacher.services.count %> services disponibles </strong> &nbsp; <i class="fas fa-angle-right"></i>
                            </a>
                            <% end %>

                        </div>

                    </div>

                </div>
            </div>

            <% end %>

        </div>
    </div>
</section>

app/views/teachers/show.html.erb
<main>

    <%= render partial: 'layouts/header_profile', locals: {page_type: 'teacher'} %>

    <section class="pt-5 pt-lg-0 bg-transparent">
        <div class="container">
            <div class="row">

                <%= render partial: 'layouts/card_profile', locals: {page_type: 'teacher'} %>

                <div class="col-md-8 mt-lg-5 mb-5">

                    <!-- General -->

                    <!-- Timeline -->
                    <div class="card">
                        <div class="card-body">
                            <!-- Badges -->
                            <div class="d-lg-flex">
                                <a class="media d-flex align-items-center mr-lg-5 mb-3 mb-lg-0">
                                    <div class="icon icon-sm icon-shape rounded-circle icon-yellow">
                                        <i class="fas fa-user-graduate"></i>
                                    </div> &nbsp; <div class="media-body pl-2">
                                        <span class="h6">
                                            <%=@teacher.sub_categories.count %> compétence(s)</span>
                                    </div>
                                </a>
                                <a class="media d-flex align-items-center mr-lg-5 mb-3 mb-lg-0">
                                    <div class="icon icon-sm icon-shape rounded-circle icon-blue">
                                        <i class="fas fa-stream"></i>
                                    </div> &nbsp; <div class="media-body pl-2">
                                        <span class="h6">
                                            <%=@teacher.services.count %> service(s)</span>
                                    </div>
                                </a>
                                <a class="media d-flex align-items-center mb-3 mb-lg-0">
                                    <div class="icon icon-sm icon-shape rounded-circle icon-red">
                                        <i class="fas fa-warehouse"></i>
                                    </div> &nbsp; <div class="media-body pl-2">
                                        <span class="h6">
                                            <%= @teacher.establishments.count %> établissement(s)</span>
                                    </div>
                                </a>
                            </div>
                            <div class="pt-5 mt-5 delimiter-top">
                                <!-- Interests -->
                                <h6>
                                    <div class="icon icon-sm icon-shape rounded-circle icon-yellow">
                                        <i class="fas fa-user-graduate"></i>
                                    </div> &nbsp; Compétences
                                </h6>
                                <div>
                                    <% @teacher.sub_categories.each do |sub| %>
                                    <span class="badge badge-lg badge-info mr-2 mb-2">
                                        <%= sub.title %>
                                        <% if current_teacher == @teacher %>
                                        <a href="<%= teacher_teacher_cat_path(current_teacher, sub)%>" class="text-light"
                                            data-toggle="tooltip" data-original-title="Remove item" data-method="DELETE"
                                            data-confirm='Vous allez vous supprimer la catégorie "<%=sub.title%>". ÊtesVeuillez confirmer.'>
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                        <% end %>
                                    </span>
                                    <%end%>
                                </div>
                                <br>
                                <% if current_teacher == @teacher %>

                                <div class="d-flex justify-content-between text-center">
                                    <span class="badge badge-lg badge-info mr-2 mb-2" id="hidden">Nouvelle compétence</span>
                                    <div id="jquery">
                                        <%= form_tag(teacher_teacher_cats_path(@teacher)) do %>
                                        <div class="d-flex flex-row">
                                            <%= select_tag 'sub_category_id', options_from_collection_for_select(@sub_categories, "id", "title"), class: "form-control-sm mx-1" %>
                                            <%= submit_tag("Ajouter", class: "btn-sm btn-warning") %>
                                        </div>
                                        <% end %>
                                    </div>
                                    <% end %>
                                </div>
                                <div class="pt-5 mt-5 delimiter-top">
                                    <!-- Interests -->
                                    <h6>
                                        <div class="icon icon-sm icon-shape rounded-circle icon-blue">
                                            <i class="fas fa-stream"></i>
                                        </div> &nbsp; Services proposés
                                    </h6>
                                    <div class="row">
                                        <% @teacher.services.each do |service| %>
                                        <div class="col-lg-6 mt-4">
                                            <div class="card bg-secondary shadow-sm border-0">
                                                <div class="media align-items-center p-3">
                                                    <a href="<%=establishment_path(service.establishment)%>" class="avatar rounded-circle mr-2">
                                                        <%= image_tag service.establishment.avatar.variant(resize: "100x100"), style: "max-width:50px; max-height:50px" %>

                                                    </a>
                                                    <div class="media-body">
                                                        <h6 class="text-sm mb-0"><span class="text-primary"> <strong>
                                                                    <%= service.name %></strong></span></h6>
                                                        <p class="text-sm mb-0">
                                                            <%= service.sub_category.title.upcase %>
                                                        </p>
                                                        <p class="text-sm mb-0">Lieu:
                                                            <%= service.establishment.name%>
                                                        </p>
                                                        <a href="<%=service_events_path(service)%>"><strong>Réserver un
                                                                créneau </strong><i class="fas fa-arrow-right"></i></a>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <% end %>
                                    </div>
                                </div>
                                <div class="pt-5 mt-5 delimiter-top">
                                    <!-- Endorsements -->
                                    <h6>
                                        <div class="icon icon-sm icon-shape rounded-circle icon-red">
                                            <i class="fas fa-warehouse"></i>
                                        </div> &nbsp; Établissement(s)
                                    </h6>
                                    <div class="row">
                                        <% @teacher.establishments.each do |establishment| %>
                                        <div class="col-lg-6 mt-4">
                                            <div class="card bg-secondary shadow-sm border-0">
                                                <div class="media align-items-center p-3">
                                                    <a href="#" class="avatar rounded-circle mr-2">
                                                        <%= image_tag establishment.avatar.variant(resize: "100x100"), style: "max-width:50px; max-height:50px"%>
                                                    </a>
                                                    <div class="media-body">
                                                        <h6 class="text-sm mb-0"> <a href="<%=establishment_path(establishment)%>">
                                                                <%= establishment.name %></a></h6>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <% end %>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>

</main>