config/routes.rb
Rails.application.routes.draw do
  devise_for :establishments
  devise_for :teachers
  devise_for :students

  root 'home#index'

  resources :students, only: [:show] do
    get '/dashboard', to: 'students#dashboard', as: 'dashboard'
  end

  resources :teachers, only: [:index, :show] do
    resources :establishments, only: [:index]
    resources :services, only: [:index]
    resources :teacher_cats, only: [:create, :destroy]
    get '/dashboard', to: 'teachers#dashboard', as: 'dashboard'
  end
  
  resources :establishments, only: [:index, :show] do
    resources :teachers, only: [:index]
    resources :services, only: [:index]
    get '/dashboard', to: 'establishments#dashboard', as: 'dashboard'

  end

  resources :resources, only: [:show, :create, :destroy, :edit] do
    resources :teachers, only: [:show]
  end

  resources :services, only: [:index, :create, :destroy] do
    resources :events, only: [:index, :create]
  end

  resources :events, only: [:show, :edit, :destroy]

end

app/models/establishment.rb
class Establishment < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :siret, presence: true
  validates :address, presence: true
  validates :phone, presence: true

  has_many :services, dependent: :destroy
  has_many :teachers, -> { distinct }, through: :services
  has_many :resources, dependent: :destroy
  has_many :events, through: :resources
  has_one_attached :avatar

  geocoded_by :address
  after_validation :geocode
  
  after_create :welcome_send, :avatar_attach

  def upcoming_events
    events.order(start_time: :asc).select { |e| e.start_time > (DateTime.now) }
  end

  def past_events
    events.order(start_time: :asc).select { |e| e.start_time <= (DateTime.now) }
  end

  def avatar_attach
    temp_user = self
    temp_user.avatar.attach(io: File.open("app/assets/images/neutral.jpeg"), filename: 'avatar')
  end


  def welcome_send
    ContactMailer.welcome_send(self).deliver_now
  end
  
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
before_action :filter_on_signed_in, only: [:dashboard]
before_action :page_belongs_to_user?, only: [:dashboard]



  def show
    @establishment = Establishment.find(params[:id])
    
    @teachers_all = Teacher.all.order(:email)
    @teachers_all =  @teachers_all.select {|s| !@establishment.teachers.include?(s)}

    @sub_cat_hash = Hash.new
    @establishment.teachers.each do |teacher|
      teacher.sub_categories.each do |sub_cat|
        @sub_cat_hash[sub_cat.title] ||= []
        @sub_cat_hash[sub_cat.title] << teacher
      end
    end
  end

  def index
    @q = Establishment.ransack(params[:q])
    @ransack = @q.result(distinct: true)
    if params[:teacher_id]
      @teacher = Teacher.find(params[:teacher_id])
      @establishments = @teacher.establishments
    else
      @establishments = Establishment.all.order(name: :asc)
    end
  end

  def dashboard
    unless current_user == Establishment.find(params[:establishment_id])
      flash[:danger] = "Vous n'êtes pas autorisé à accéder à cette page"
      redirect_to root_path
      return
    end

    @establishment = current_user
    @events = @establishment.events

    @resources = @establishment.resources.order(name: :asc)
    @resource = Resource.new

    @services = @establishment.services.order(created_at: :desc)
    @service = Service.new

    @teachers = Teacher.all.order(email: :asc)
    @my_teachers = @establishment.teachers

    @sub_categories = SubCategory.all.order(title: :asc)

    if params[:search_resource]
      @resource_calendar = Resource.find(params[:search_resource])
    else 
      @resource_calendar = @resources.first
    end 

    @participants = []
    @events.each do |event|
      @participants << event.student
    end 
    @participant = @participants.uniq!

    if @participant == nil
    @participant = []
    end 

    p "*" * 50
    p @participant.inspect
    p "*" * 50
    p @participant.class


  end

  private

  def filter_user_allowed
    if params[:establishment_id]
      user_id = params[:establishment_id]
    elsif params[:id]
      user_id = params[:id]
    else
      user_id = 0
    end
      
    unless current_user == Establishment.find(user_id)
      flash[:danger] = "Vous n'êtes pas autorisé à accéder à cette page"
      redirect_to root_path
    end
  end
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/views/establishments/_dash-accueil.html.erb
<!-- UPCOMING EVENTS -->

<!-- section title -->
<h2 class="heading h4 font-weight-bold">

    <div class="row d-flex justify-content-between">

        <div class="col 10">
            <div class="icon icon-sm icon-shape rounded-circle icon-red">
                <i class="far fa-calendar-check"></i>
            </div>
            &nbsp; Rendez-vous à venir :
            <%= current_user.upcoming_events.count %>
        </div>

        <div class="col-2">
            <a id="dash-event-show" style="cursor: pointer">
                <i class="fas fa-arrow-circle-down fa-xs"></i>
            </a>
        </div>

    </div>

</h2>


<!-- if NO current user events  -->
<% if current_user.upcoming_events == nil %>

<div class="mt-4">
    <span class="mb-4"><i class="fas fa-info-circle"></i> &nbsp; Votre historique de réservations est
        vide</span>
</div>

<div class="mt-4">
    <a href="<%=teachers_path%>" class="btn-sm btn-danger btn-circle btn-translate--hover btn-icon mr-sm-4 scroll-me"
        data-scroll-to-offset="40">
        <span class="btn-inner--text">Contacter un professeur</span>
        <span class="btn-inner--icon"><i class="fas fa-angle-right"></i></span>
    </a>
</div>

<% end %>

<hr>

<!-- resources list (CARD) -->

<div class="row pb-5" id="dash-event-hide">

    <% if current_user.upcoming_events.any? %>

    <% current_user.upcoming_events.each do |event|%>

    <div class="col-lg-3 pt-3">
        <div class="card overflow-hidden" data-animate-hover="2" id="dash-card">

            <div class="card-body text-center">

                <!-- title -->
                <h5 class="card-title h6 mb-4">
                    <%= Service.find(event.service_id).name %>
                </h5>

                <!-- date -->
                <p class="text-muted m-3">
                    <i class="fas fa-calendar-alt"></i> &nbsp;
                    <%=(event.start_time).strftime("%d/%m/%Y")%>
                </p>

                <hr class="m-3">

                <!-- time -->
                <p class="text-muted m-3">
                    <i class="far fa-clock"></i> &nbsp;
                    <%= Time.at(event.start_time).strftime("%Hh%M") %>
                    &bull;
                    <strong>

                        <% if Time.at(event.duration).utc.strftime("%Hh%M") == "00h30" || Time.at(event.duration).utc.strftime("%Hh%M") == "00h15" || Time.at(event.duration).utc.strftime("%Hh%M") == "00h45" %>

                        <%= Time.at(event.duration).utc.strftime("%M") %> min

                        <% else %>

                        <%= Time.at(event.duration).utc.strftime("%Hh") %>

                        <% end %>

                    </strong>
                </p>

                <hr class="m-3">

                <!-- description -->
                <!-- <p class="text-muted">
                    <strong>Détails</strong> <br>
                    <%=event.name%>
                </p> -->

                <!-- edit / delete icons -->
                <div class="mt-3">
                    <a href="<%= event_path(event) %>" class="text-light">
                        <i class="fas fa-info-circle text-info fa-lg"></i>
                    </a>
                    &nbsp; &nbsp; &nbsp;
                    <a href="<%= event_path(event) %>" class="text-light" data-toggle="tooltip" data-original-title="Remove item"
                        data-method="DELETE" data-confirm="Vous allez supprimer l'évènement '<%=event.name%>'. Veuillez confirmer.">
                        <i class="fas fa-trash-alt text-danger"></i>
                    </a>
                </div>

            </div>
        </div>

    </div>

    <% end %>

</div>
<% end %>


<!-- PARTICIPANT -->

<!-- section title -->
<h2 class="heading h4 font-weight-bold">

    <div class="row d-flex justify-content-between">

        <div class="col 10">
            <div class="icon icon-sm icon-shape rounded-circle icon-green">
                <i class="fas fa-users"></i>
            </div>
            &nbsp; Participants inscrits :
            <%= @participant.length %>
        </div>

        <div class="col-2">
            <a id="dash-part-show" style="cursor: pointer">
                <i class="fas fa-arrow-circle-down fa-xs"></i>
            </a>
        </div>

    </div>

</h2>


<!-- cards -->
<div class="row pb-5" id="dash-part-hide">

    <% @participant.each do |participant| %>

    <% if participant.created_at.year == DateTime.now.year %>

    <div class="col-lg-6 pt-3">
        <div class="card overflow-hidden" data-animate-hover="2" id="dash-card">

            <div class="card-body text-center">

                <!-- name -->
                <h5 class="card-title h6 mb-0">
                    <%= participant.first_name %>
                    <%= participant.last_name.upcase %>
                </h5>

                <!-- registred since -->
                <p class="text-muted m-3">
                    <%= participant.created_at.strftime("Inscrit(e) depuis le %d/%m/%Y") %>
                </p>

                <hr class="m-3">

                <!-- phone number -->
                <p class="text-muted">
                    <i class="fas fa-phone"></i> &nbsp;
                    <%= participant.phone %>
                </p>

                <hr class="m-3">

                <!-- email -->
                <p class="text-muted">
                    <i class="far fa-envelope"></i> &nbsp;
                    <%= participant.email %>
                </p>

                <!-- see profile -->
                <div class="mt-3">
                    <a href="<%= student_path(@participant)%>" class="text-success">
                        Voir le profil &nbsp; <i class="fas fa-user-circle"></i>
                    </a>
                </div>

            </div>

        </div>
    </div>

    <% end %>

    <% end %>

</div>

<hr>


<!-- TEACHERS -->

<!-- section title -->
<h2 class="heading h4 font-weight-bold">

    <div class="row d-flex justify-content-between">

        <div class="col 10">
            <div class="icon icon-sm icon-shape rounded-circle icon-yellow">
                <i class="fas fa-chalkboard-teacher"></i>
            </div>
            &nbsp; Intervenants affiliés :
            <%= @my_teachers.count %>
        </div>

        <div class="col-2">
            <a id="dash-teacher-show" style="cursor: pointer">
                <i class="fas fa-arrow-circle-down fa-xs"></i>
            </a>
        </div>

    </div>

</h2>


<!-- cards -->
<div class="row pb-5" id="dash-teacher-hide">

    <% @my_teachers.each do |teacher| %>

    <div class="col-lg-3 pt-3">
        <div class="card overflow-hidden" data-animate-hover="2">

            <!-- avatar -->
            <div class="overflow-hidden">
                <div class="animate-this text-center">

                    <% if teacher.avatar.attached? %>
                    <%= image_tag teacher.avatar, class: "image-size" %>
                    <% else %>
                    <a href="<%= teacher_path(teacher) %>">
                        <%= image_tag ("prof2.jpg"), class: "image-size" %>
                    </a>
                    <%end%>

                </div>
            </div>

            <div class="card-body text-center" id="dash-card">

                <!-- name -->
                <h5 class="card-title h6 mb-0"><a href="<%= teacher_path(teacher) %>" class="text-dark">
                        <%=teacher.first_name%> <br>
                        <%= teacher.last_name.upcase %></a></h5>

                <!-- services -->
                <p class="text-muted mb-0">
                    <%teacher.sub_categories.each_with_index do |sub_cat, ind|%>
                    <%unless ind == 0 %>
                    -
                    <%end%>
                    <%=sub_cat.title%>
                    <%end%>
                </p>

                <!-- see profile -->
                <div class="mt-3">
                    <a href="<%=teacher_path(teacher.id)%>" class="text-warning">
                        Voir le profil &nbsp; <i class="fas fa-user-circle"></i>
                    </a>
                </div>

            </div>

        </div>
    </div>

    <% end %>

</div>

<hr>


<!-- SERVICES -->

<!-- section title -->
<h2 class="heading h4 font-weight-bold">

    <div class="row d-flex justify-content-between">

        <div class="col 10">
            <div class="icon icon-sm icon-shape rounded-circle icon-blue">
                <i class="fas fa-stream"></i>
            </div>
            &nbsp; Services proposés :
            <%= @services.count %>
        </div>

        <div class="col-2">
            <a id="dash-service-show" style="cursor: pointer">
                <i class="fas fa-arrow-circle-down fa-xs"></i>
            </a>
        </div>

    </div>

</h2>


<!-- cards -->
<div class="row pb-5" id="dash-service-hide">

    <% @services.each do |service| %>

    <div class="col-lg-3 pt-3">
        <div class="card overflow-hidden" data-animate-hover="2">

            <div class="card-body text-center" id="dash-card">

                <!-- name -->
                <h5 class="h6 mb-4">
                    <a href="<%= service_path(service) %>" class="text-dark">
                        <%=service.name%>
                    </a>
                </h5>

                <div class="mt-3">

                    <!-- duration -->
                    <p class="text-muted mb-2">
                        <i class="far fa-clock"></i>
                        <%=service.duration/60%> min </p>

                    <hr class="m-3">

                    <!-- teacher -->
                    <a href="<%=teacher_path(service.teacher)%>" class="text-muted mb-0">
                        <strong>Professeur</strong> <br>
                        <%=service.teacher.first_name%>
                        <%=service.teacher.last_name.upcase%>
                    </a>

                    <hr class="m-3">

                    <!-- room / resource -->
                    <p class="text-muted">
                        <strong>Ressource</strong><br>
                        <%=service.resource.name%>
                    </p>

                </div>

            </div>

        </div>
    </div>
    <% end %>

</div>

app/views/establishments/dashboard.html.erb
<%= render 'layouts/flash' %>

<main class="main">

    <%= render 'dash-nav' %>

    <div class="content-inner content-docs">
        <div class="container-fluid">

            <!-- ACCUEIL -->
            <div class="pt-3 pb-4 mb-4 border-bottom">
                <div class="row">
                    <div class="col-lg-12">

                        <div id="dash-accueil">
                            <br>
                                <%= render 'dash-accueil' %>
                        </div>

                    </div>
                </div>
            </div>

            <!-- RESERVATIONS -->
            <div class="pt-3 pb-4 mb-4 border-bottom">
                <div class="row">
                    <div class="col-lg-12">

                        <div id="dash-resa">
                            <br>
                                <%= render 'dash-resa' %>
                        </div>

                    </div>
                </div>
            </div>

            <!-- PARTICIPANTS -->
            <div class="pt-3 pb-4 mb-4 border-bottom">
                <div class="row">
                    <div class="col-lg-12">

                        <div id="dash-particip">
                            <br>
                                <%= render 'dash-particip' %>
                        </div>

                    </div>
                </div>
            </div>

            <!-- PARAMETRES -->
            <div class="pt-3 pb-4 mb-4 border-bottom">
                <div class="row">
                    <div class="col-lg-12">

                        <div id="dash-param">
                            <br>
                                <%= render 'dash-param' %>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

</main>

app/views/establishments/index.html.erb
<!-- TOP SLICE -->
<section class="slice slice-lg section-rotate">
    <div class="section-inner bg-gradient-info">
        <span class="section-inner-bg"></span>
    </div>

    <!-- main text -->
    <div class="container mt-xl">
        <div class="row align-items-center">
            <div class="col-lg-10 pl-0">
                <h1 class="text-white mb-3">Les Établissements</h1>
                <p class="lead text-white lh-180">Retrouvez ici tous les établissements inscrits sur AwaBooking !</p>


                <!-- search form -->
                <div class="row align-items-center pt-3">

                    <!-- input field -->
                    <div class="col-6">
                        <%= search_form_for @q do |f| %>
                        <%= f.search_field :name_cont, class: "form-control", placeholder: "Trouver un établissement par nom" %>
                    </div>

                    <!-- research button -->
                    <div class="col-3">
                        <%= f.submit "Rechercher", class: "btn-sm btn-circle btn-info" %>
                    </div>
                    <% end %>

                    <!-- all establishments - shows only when research exists -->
                    <% if @q.name_cont %>
                    <div class="col-3">
                        <%= link_to "Tous les établissements", establishments_path, class: "btn-sm btn-circle btn-danger" %>
                    </div>
                    <% end %>

                </div>
            </div>
        </div>
    </div>
</section>


<section class="slice-lg bg-transparent" id="top-index">
    <div class="container mt-5">
        <div class="row">

            <% @ransack.each do |establishment| %>

            <!-- cards -->
            <div class="col-lg-3 pt-5">
                <div class="card overflow-hidden" data-animate-hover="2" id="card-index">

                    <div class="overflow-hidden">
                        <div class="animate-this text-center">

                            <!-- avatar -->
                            <% if establishment.avatar.attached? %>
                            <%= image_tag establishment.avatar, class: "image-size" %>
                            <% else %>
                            <a href="<%= establishment_path(establishment) %>">
                                <%= image_tag ("prof2.jpg"), class: "image-size" %>
                            </a>
                            <% end %>

                        </div>
                    </div>

                    <div class="card-body text-center">

                        <!-- name -->
                        <h5 class="card-title mb-0">
                            <a href="<%= establishment_path(establishment) %>" class="text-dark">
                                <%=establishment.name%>
                            </a>
                        </h5>

                        <div class="mt-3">

                        <!-- see profile -->
                            <a href="<%=establishment_path(establishment.id)%>" class="text-danger">
                                Voir le profil &nbsp; <i class="fas fa-user-circle"></i>
                            </a>

                            <!-- number of services availables -->
                            <hr class="m-2">

                            <!-- no service -->
                            <% if establishment.services.count == 0 %>
                            <a class="text-light">Pas de service disponible</a>

                            <!-- one service  -->
                            <% elsif establishment.services.count == 1 %>
                            <a href="<%=establishment_services_path(establishment.id)%>" class="text-info">
                                <strong><%= establishment.services.count %> service disponible</strong>  &nbsp; <i class="fas fa-angle-right"></i>
                            </a>
                            
                            <!-- several services  -->
                            <% else %>
                            <a href="<%=establishment_services_path(establishment.id)%>" class="text-info">
                                <strong><%= establishment.services.count %> services disponibles</strong>  &nbsp; <i class="fas fa-angle-right"></i>
                            </a>
                            <% end %>

                        </div>

                    </div>

                </div>
            </div>

            <% end %>

        </div>
    </div>
</section>

app/views/establishments/show.html.erb
<main>

    <!-- HEADER -->
    <%= render partial: 'layouts/header_profile', locals: {page_type: 'establishment'} %>

    <section class="pt-5 pt-lg-0 bg-transparent">
        <div class="container">
            <div class="row">

                <!-- STICKY PROFILE CARD  -->
                <%= render partial: 'layouts/card_profile', locals: {page_type: 'establishment'} %>

                <div class="col-md-8 mt-lg-5 mb-5">

                    <!-- MAIN CARD -->
                    <div class="card">
                        <div class="card-body ">

                            <!-- TOP section -->
                            <div class="d-lg-flex mt-3">
                                <a class="media d-flex align-items-center mr-lg-5 mb-3 mb-lg-0">
                                    <div class="icon icon-sm icon-shape rounded-circle icon-blue">
                                        <i class="fas fa-stream"></i>
                                    </div> &nbsp;
                                    <div class="media-body pl-2">
                                        <span class="h6">
                                            <%= @establishment.services.count %> service(s) proposé(s)</span>
                                    </div>
                                </a>
                                <a class="media d-flex align-items-center mr-lg-5 mb-3 mb-lg-0">
                                    <div class="icon icon-sm icon-shape rounded-circle icon-yellow">
                                        <i class="fas fa-chalkboard-teacher"></i>
                                    </div> &nbsp;
                                    <div class="media-body pl-2">
                                        <span class="h6">
                                            <%= @establishment.teachers.length %> professeurs</span>
                                    </div>
                                </a>
                            </div>

                            <!-- ...line... -->
                            <div class="pt-5 mt-5 delimiter-top"></div>

                            <!-- SERVICES  -->
                            <!-- title -->
                            <h6>
                                <div class="icon icon-sm icon-shape rounded-circle icon-blue">
                                    <i class="fas fa-stream"></i>
                                </div> &nbsp;
                                Services
                            </h6>

                            <!-- cards -->
                            <div class="pt-3 row">

                                <% @establishment.services.each do |service| %>

                                <div class="col-lg-4 pt-3">
                                    <div class="card overflow-hidden" data-animate-hover="2" id="dash-card">

                                        <div class="card-body text-center">

                                            <!-- name -->
                                            <h5 class="card-title mb-4">
                                                <a href="<%= service_path(service) %>" class="text-dark">
                                                    <%=service.name%>
                                                </a>
                                            </h5>

                                            <div class="mt-3">

                                                <!-- duration -->
                                                <p class="text-muted mb-2">
                                                    <i class="far fa-clock"></i>
                                                    <%=service.duration/60%> min </p>
                                                <hr class="m-3">

                                                <!-- teacher -->
                                                <strong>Intervenant</strong>
                                                <a href="<%=teacher_path(service.teacher)%>" class="text-warning mb-0"><br>
                                                    <%=service.teacher.first_name%> <br>
                                                    <%=service.teacher.last_name.upcase%>
                                                </a>

                                                <hr class="m-3">

                                                <!-- book event -->
                                                <a href="<%=service_events_path(service.id)%>" class="text-info">
                                                    <u>Réserver </u> &nbsp; <i class="fas fa-angle-right"></i>
                                                </a>

                                            </div>

                                        </div>

                                    </div>
                                </div>

                                <% end %>

                            </div>

                            <!-- ...line... -->
                            <div class="pt-5 mt-5 delimiter-top"></div>

                            <!-- TEACHERS -->
                            <!-- title -->
                            <h6>
                                <div class="icon icon-sm icon-shape rounded-circle icon-yellow">
                                    <i class="fas fa-chalkboard-teacher"></i>
                                </div> &nbsp;
                                Professeur(s) à
                                <%= @establishment.name %>
                            </h6>

                            <!-- cards -->
                            <div class="pt-3 row">

                                <% @establishment.teachers.each do |teacher| %>

                                <div class="col-lg-4 pt-3">
                                    <div class="card overflow-hidden" data-animate-hover="2" id="card-index">

                                        <div class="overflow-hidden">
                                            <div class="animate-this text-center">

                                                <!-- avatar -->
                                                <% if teacher.avatar.attached? %>
                                                <%= image_tag teacher.avatar, class: "image-size" %>
                                                <% else %>
                                                <a href="<%= teacher_path(teacher) %>">
                                                    <%= image_tag ("prof2.jpg"), class: "image-size" %>
                                                </a>
                                                <%end%>

                                            </div>
                                        </div>

                                        <div class="card-body text-center">

                                            <!-- name -->
                                            <h5 class="card-title mb-0"><a href="<%= teacher_path(teacher) %>" class="text-dark">
                                                    <%=teacher.first_name%>
                                                    <%= teacher.last_name %></a></h5>

                                            <!-- services categories -->
                                            <p class="text-muted mb-0">
                                                <%teacher.sub_categories.each_with_index do |sub_cat, ind|%>
                                                <%unless ind == 0 %>
                                                -
                                                <%end%>
                                                <%=sub_cat.title%>
                                                <%end%>
                                            </p>

                                            <!-- see profile -->
                                            <div class="mt-3">
                                                <a href="<%=teacher_path(teacher.id)%>" class="text-danger">
                                                    Voir le profil &nbsp; <i class="fas fa-user-circle"></i>
                                                </a>

                                                <!-- number of services availables -->
                                                <hr class="m-2">

                                                <!-- no service -->
                                                <% if teacher.services.count == 0 %>
                                                <a class="text-light">Pas de service disponible</a>

                                                <!-- one service  -->
                                                <% elsif teacher.services.count == 1 %>
                                                <a href="<%=teacher_services_path(teacher.id)%>" class="text-info">
                                                    <%= teacher.services.count %> service disponible &nbsp; <i class="fas fa-angle-right"></i>
                                                </a>

                                                <!-- several services  -->
                                                <% else %>
                                                <a href="<%=teacher_services_path(teacher.id)%>" class="text-info">
                                                    <%= teacher.services.count %> services disponibles &nbsp; <i class="fas fa-angle-right"></i>
                                                </a>
                                                <% end %>

                                            </div>

                                        </div>

                                    </div>
                                </div>

                                <% end %>
                            </div>

                        </div>
                    </div>

                </div>

            </div>
        </div>
    </section>

</main>