config/routes.rb
Rails.application.routes.draw do
  devise_for :establishments
  devise_for :teachers
  devise_for :students

  root 'home#index'

  resources :students, only: [:show] do
    get '/dashboard', to: 'students#dashboard', as: 'dashboard'
  end

  resources :teachers, only: [:index, :show] do
    resources :establishments, only: [:index]
    resources :services, only: [:index]
    resources :teacher_cats, only: [:create, :destroy]
    get '/dashboard', to: 'teachers#dashboard', as: 'dashboard'
  end
  
  resources :establishments, only: [:index, :show] do
    resources :teachers, only: [:index]
    resources :services, only: [:index]
    get '/dashboard', to: 'establishments#dashboard', as: 'dashboard'

  end

  resources :resources, only: [:show, :create, :destroy, :edit] do
    resources :teachers, only: [:show]
  end

  resources :services, only: [:index, :create, :destroy] do
    resources :events, only: [:index, :create]
  end

  resources :events, only: [:show, :edit, :destroy]

end

app/views/layouts/_card_profile.html.erb
<div class="col-md-4 mb-5">
    <div data-toggle="sticky" data-sticky-offset="100" id="card-profile-sticky">
        <div class="card card-profile border-0 shadow  text-center">

            <% if page_type == 'establishment' %>
            <div class="card-profile-cover">
                <%= image_tag 'background_establishment_card.jpg', class: 'card-img-top', alt: 'card-background' %>
            </div>
            <% if @establishment.avatar.attached? %>
            <a>
                <%= image_tag @establishment.avatar, class: 'card-profile-image avatar shadow', style: 'height: 150px; width: auto', alt: 'card-picture' %>
            </a>
            <% else %>
            <a>
                <%= image_tag 'neutral.jpeg', class: "card-profile-image avatar shadow", alt: 'card-picture-default' %>
            </a>
            <% end %>
            <div class="card-body">
                <div class="mb-3">
                    <h4 class="mb-0">
                        <%= @establishment.name %>
                    </h4>
                    <h6 class="mb-0 pt-3">Téléphone</h6>
                    <span class="btn-inner--icon"><i class="fas fa-phone"></i></span>
                    <span class="text-muted">
                        <%= @establishment.phone %></span>
                    <h6 class="mb-0 pt-3">Email</h6>
                    <span class="btn-inner--icon"><i class="fas fa-envelope"></i></span>
                    <span class="text-muted">
                        <%= @establishment.email %></span>
                </div>
                <% if current_user == @establishment %>
                <div class="pt-4 mt-4 delimiter-top">
                    <div class="btn-group shadow rounded-circle">

                        <%= link_to '<i class="fas fa-pen"></i> &nbsp; Modifier mon profil'.html_safe, edit_establishment_registration_path, class: "btn btn-sm btn-outline-danger btn-circle btn-icon", id: "btn-group-settings"  %></span>
                    </div>
                </div>
                <% end %>
            </div>
            <% elsif page_type == 'teacher' %>
            <div class="card-profile-cover">
                <%= image_tag 'background_teacher_card.jpg', class: 'card-img-top', alt: 'card-background' %>
            </div>
            <% if @teacher.avatar.attached? %>
            <a>
                <%= image_tag @teacher.avatar, class: "card-profile-image avatar shadow", style: "height: 150px; width: auto", alt: 'card-picture' %>
            </a>
            <% else %>
            <a>
                <%= image_tag 'neutral.jpeg', class: "card-profile-image avatar shadow", alt: 'card-picture-default' %>
            </a>
            <% end %>
            <div class="card-body">
                <div class="mb-3">
                    <h6 class="mb-0">
                        <%= @teacher.first_name %> <strong>
                            <%= @teacher.last_name %></strong></h6>
                    <h6 class="mb-0 pt-3">Téléphone</h6>
                    <span class="btn-inner--icon"><i class="fas fa-phone"></i></span>
                    <span class="text-muted">
                        <%= @teacher.phone %></span>
                    <h6 class="mb-0 pt-3">Email</h6>
                    <span class="btn-inner--icon"><i class="fas fa-envelope"></i></span>
                    <span class="text-muted">
                        <%= @teacher.email %></span>
                </div>
                <span class="text-muted"><i class="fas fa-map-marker mr-2"></i>
                    <%= @teacher.address %></span>
                <% if current_user == @teacher %>
                <div class="pt-4 mt-4 delimiter-top">
                    <div class="btn-group shadow rounded-circle">
                        <%= link_to '<i class="fas fa-pen"></i> &nbsp; Modifier mon profil'.html_safe, teacher_registration_path, class: "btn btn-sm btn-outline-danger btn-circle btn-icon", id: "btn-group-settings"  %></span>
                    </div>
                </div>
                <% end %>
            </div>
            <% elsif page_type == 'student' %>
            <div class="card-profile-cover">
                <%= image_tag 'background_student_card.jpg', class: 'card-img-top', alt: 'card-background' %>
            </div>
            <% if @student.avatar.attached? %>
            <a>
                <%= image_tag @student.avatar, style: "height: 150px; width: auto", class: "card-profile-image avatar shadow", alt: 'card-picture' %>
            </a>
            <% else %>
            <a>
                <%= image_tag 'neutral.jpeg', class: "card-profile-image avatar shadow", alt: 'card-picture-default' %>
            </a>
            <% end %>

            <div class="card-body">
                <div class="mb-3">
                    <h6 class="mb-0">
                        <%= @student.first_name %> <strong>
                            <%= @student.last_name %></strong></h6>
                    <h6 class="mb-0 pt-3">Téléphone</h6>
                    <span class="btn-inner--icon"><i class="fas fa-phone"></i></span>
                    <span class="text-muted">
                        <%= @student.phone %></span>
                    <h6 class="mb-0 pt-3">Email</h6>
                    <span class="btn-inner--icon"><i class="fas fa-envelope"></i></span>
                    <span class="text-muted">
                        <%= @student.email %></span>
                </div>
                <% if current_user == @student %>
                <div class="pt-4 mt-4 delimiter-top">
                    <div class="btn-group shadow rounded-circle">
                        <%= link_to '<i class="fas fa-pen"></i> &nbsp; Modifier mon profil'.html_safe, edit_student_registration_path, class: "btn btn-sm btn-outline-danger btn-circle btn-icon" %></span>
                    </div>
                </div>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
<%if key != "success" && key != "danger" %>
<%type = "info"%>
<%else%>
<%type = key%>
<%end%>
<div class="alert alert-<%=type%>", id="alerts">
  <%= value %>
</div>
<% end %>

app/views/layouts/_footer-perso.html.erb
<footer class="footer-dark bg-gradient-dark footer-rotate">

        <div class="container">
    
    <!-- ...................USER LOGGED IN................... -->
    
            <% if current_user %>
    
            <!-- top - logo + navig menu -->
            <div class="row d-flex justify-content-around align-items-center px-3">
    
                <a href="<%= root_path %>">
                    <%= image_tag "AwaBooking.png", :alt => "logo" -%>
                </a>
    
                <!-- user profile menu -->
                <div class="foot-links">
    
                    <!-- student -->
                    <% if current_student %>
                    <h6 class="heading text-white mb-3">Bienvenue
                        <%= current_student.first_name %>
                    </h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= get_profil(current_user) %>">Mon profil</a></li>
                        <li><a href="<%= edit_student_registration_path %>">Éditer mon profil</a></li>
                        <li><a href="<%= get_dashboard(current_user) %>">Dashboard</a></li>
                    </ul>
    
                    <!-- teacher -->
                    <% elsif current_teacher %>
                    <h6 class="heading text-white mb-3">Bienvenue
                        <%= current_teacher.first_name %>
                    </h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= get_profil(current_user) %>">Mon profil</a></li>
                        <li><a href="<%= edit_teacher_registration_path %>">Éditer mon profil</a></li>
                        <li><a href="<%= get_dashboard(current_user) %>">Dashboard</a></li>
                    </ul>
    
                    <!-- establishment -->
                    <% elsif current_establishment %>
                    <h6 class="heading text-white mb-3">Bienvenue
                        <%= current_establishment.name %>
                    </h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= get_profil(current_user) %>">Mon Profil</a></li>
                        <li><a href="<%= edit_establishment_registration_path %>">Éditer mon profil</a></li>
                        <li><a href="<%= get_dashboard(current_user) %>">Dashboard</a></li>
                    </ul>
                    <% end %>
    
                </div>
    
                <!-- navigation menu -->
                <div class="foot-links">
                    <h6 class="heading text-white mb-3">Services</h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= root_path %>">Tous nous services</a></li>
                        <li><a href="<%= teachers_path %>">Tous nous professeur</a></li>
                        <li><a href="<%= establishments_path %>">Tous nous établissement</a></li>
                    </ul>
                </div>
    
            </div>
    
            <!-- bottom - credits + social media -->
            <div class="row align-items-center justify-content-md-between py-4 mt-4 delimiter-top">
                <div class="col-md-6">
                    <div class="copyright text-sm font-weight-bold text-center text-md-left">
                        <strong>THP Team MONTPELLIER</strong> <a class="font-weight-light">&copy; 2018</a> <a href="https://webpixels.io/"
                         class="font-weight-regular" target="_blank">Webpixels</a>. <a class="font-weight-light">All rights reserved.</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <ul class="nav justify-content-center justify-content-md-end mt-3 mt-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" href="https://www.instagram.com/the_hacking_project/" target="_blank">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://github.com/lea-lp/Stomy-Booksy" target="_blank">
                                <i class="fab fa-github"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://fr-fr.facebook.com/thehackingproject/" target="_blank">
                                <i class="fab fa-facebook"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
    
    <!-- ...................USER LOGGED OUT................... -->
    
            <% else %>
    
            <!-- top - logo + navig menu -->
            <div class="row d-flex justify-content-between align-items-center px-3">
    
                <a href="<%= root_path %>">
                    <%= image_tag "AwaBooking.png", :alt => "logo" -%>
                </a>
    
                <!-- student -->
                <div class="foot-links ml-5">
                    <h6 class="heading text-white mb-3">Particulier</h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= new_student_session_path %>">Se connecter</a></li>
                        <li><a href="<%= new_student_registration_path %>">S'inscrire</a></li>
                        <li><a href="#we-do">En savoir plus</a></li>
                    </ul>
                </div>
    
                <!-- teacher -->
                <div class="foot-links">
                    <h6 class="heading text-white mb-3">Professeur</h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= new_teacher_session_path %>">Se connecter</a></li>
                        <li><a href="<%= new_teacher_registration_path %>">S'inscrire</a></li>
                        <li><a href="#we-do">En savoir plus</a></li>
                    </ul>
                </div>
    
                <!-- establishment -->
                <div class="foot-links">
                    <h6 class="heading text-white mb-3">Établissement</h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= new_establishment_session_path %>">Se connecter</a></li>
                        <li><a href="<%= new_establishment_registration_path %>">S'inscrire</a></li>
                        <li><a href="#we-do">En savoir plus</a></li>
                    </ul>
                </div>
    
                <!-- navigation menu -->
                <div class="foot-links">
                    <h6 class="heading text-white mb-3">Services</h6>
                    <ul class="list-unstyled">
                        <li><a href="<%= root_path %>">Tous nous services</a></li>
                        <li><a href="<%= teachers_path %>">Tous nous professeur</a></li>
                        <li><a href="<%= establishments_path %>">Tous nous établissement</a></li>
                    </ul>
                </div>
    
            </div>
    
            <!-- bottom - credits + social media -->
            <div class="row align-items-center justify-content-md-between py-4 mt-4 delimiter-top">
                <div class="col-md-6">
                    <div class="copyright text-sm font-weight-bold text-center text-md-left">
                        <strong>THP Team MONTPELLIER</strong> <a class="font-weight-light">&copy; 2018</a> <a href="https://webpixels.io/"
                         class="font-weight-regular" target="_blank">Webpixels</a>. <a class="font-weight-light">All rights reserved.</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <ul class="nav justify-content-center justify-content-md-end mt-3 mt-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" href="https://www.instagram.com/the_hacking_project/" target="_blank">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://github.com/lea-lp/Stomy-Booksy" target="_blank">
                                <i class="fab fa-github"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://fr-fr.facebook.com/thehackingproject/" target="_blank">
                                <i class="fab fa-facebook"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            
        <% end %>
    
        </div>
        
    </footer>
    
    

app/views/layouts/_footer.html.erb
<footer class="footer footer-dark bg-gradient-info footer-rotate">
	<div class="container">

		<div class="row pt-md justify-content-md-between">

			<!-- logo -->
			<div class="col-lg-3 mb-5 mb-lg-0">
				<a href="<%= root_path %>">
					<%= image_tag "AwaBookingWhite.png", :alt => "logo", class: "w-75" -%>
				</a>
				<p class="text-sm pt-4">La platerforme de réservation, </br> <strong>partout, pour tous.</strong> </p>
			</div>

			<!-- ...................USER LOGGED IN................... -->

			<% if current_user %>

			<!-- col 1 : explore -->
			<div class="col-lg-3 mb-5 mb-lg-0 pl-5">
				<h6 class="heading mb-3">Explorez</h6>
				<ul class="list-unstyled">
					<li><a href="#top">Accueil</a></li>
					<li><a href="#above-map">Carte dynamique</a></li>
					<li><a href="#we-do">Notre process</a></li>
				</ul>
			</div>

			<!-- col 2 : user type -->
			<div class="col-lg-3 mb-5 mb-lg-0">

				<!-- student -->
				<% if current_student %>
				<h6 class="heading mb-3">Bienvenue
					<%= current_student.first_name %>
				</h6>
				<ul class="list-unstyled">
					<li><a href="<%= get_profil(current_user) %>">Mon profil</a></li>
					<li><a href="<%= edit_student_registration_path %>">Éditer mon profil</a></li>
					<li><a href="<%= get_dashboard(current_user) %>">Dashboard</a></li>
				</ul>

				<!-- teacher -->
				<% elsif current_teacher %>
				<h6 class="heading mb-3">Bienvenue
					<%= current_teacher.first_name %>
				</h6>
				<ul class="list-unstyled">
					<li><a href="<%= get_profil(current_user) %>">Mon profil</a></li>
					<li><a href="<%= edit_teacher_registration_path %>">Éditer mon profil</a></li>
					<li><a href="<%= get_dashboard(current_user) %>">Dashboard</a></li>
				</ul>

				<!-- establishment -->
				<% elsif current_establishment %>
				<h6 class="heading mb-3">Bienvenue
					<%= current_establishment.name %>
				</h6>
				<ul class="list-unstyled">
					<li><a href="<%= get_profil(current_user) %>">Mon Profil</a></li>
					<li><a href="<%= edit_establishment_registration_path %>">Éditer mon profil</a></li>
					<li><a href="<%= get_dashboard(current_user) %>">Dashboard</a></li>
				</ul>
				<% end %>

			</div>



			<!-- ...................USER LOGGED OUT................... -->

			<% else %>

			<!-- col 1 : student -->
			<div class="col-lg-2 mb-5 mb-lg-0">
				<h6 class="heading mb-3">Particulier</h6>
				<ul class="list-unstyled">
					<li><a href="<%= new_student_session_path %>">Se connecter</a></li>
					<li><a href="<%= new_student_registration_path %>">S'inscrire</a></li>
					<li><a href="#we-do">En savoir plus</a></li>
				</ul>
			</div>

			<!-- col 2 : teacher -->
			<div class="col-lg-2 mb-5 mb-lg-0">
				<h6 class="heading mb-3">Professeur</h6>
				<ul class="list-unstyled">
					<li><a href="<%= new_teacher_session_path %>">Se connecter</a></li>
					<li><a href="<%= new_teacher_registration_path %>">S'inscrire</a></li>
					<li><a href="#we-do">En savoir plus</a></li>
				</ul>
			</div>

			<!-- col 3 : establishment -->
			<div class="col-lg-2 mb-5 mb-lg-0">
				<h6 class="heading mb-3">Établissement</h6>
				<ul class="list-unstyled">
					<li><a href="<%= new_establishment_session_path %>">Se connecter</a></li>
					<li><a href="<%= new_establishment_registration_path %>">S'inscrire</a></li>
					<li><a href="#we-do">En savoir plus</a></li>
				</ul>
			</div>

			<% end %>

			<!-- last col (right) : services -->
			<div class="col-lg-3 mb-5 mb-lg-0">
				<h6 class="heading mb-3">Services</h6>
				<ul class="list-unstyled">
					<li><a href="<%= services_path %>">Tous nous services</a></li>
					<li><a href="<%= teachers_path %>">Tous nous professeur</a></li>
					<li><a href="<%= establishments_path %>">Tous nous établissement</a></li>
				</ul>
			</div>

		</div>

		<!-- bottom - credits + social media -->
		<div class="row align-items-center justify-content-md-between py-4 mt-4 delimiter-top">
			<div class="col-md-6">
				<div class="copyright text-sm font-weight-bold text-center text-md-left">
					<strong class="text-white">AwaBooking</strong> <a class="font-weight-light">&copy; 2019</a> - <a class="font-weight-light">All rights reserved.</a>
				</div>
			</div>
			<div class="col-md-6">
				<ul class="nav justify-content-center justify-content-md-end mt-3 mt-md-0">
					<li class="nav-item">
						<a class="nav-link active" href="https://www.instagram.com/the_hacking_project/" target="_blank">
							<i class="fab fa-instagram"></i>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="https://github.com/lea-lp/Stomy-Booksy" target="_blank">
							<i class="fab fa-github"></i>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="https://fr-fr.facebook.com/thehackingproject/" target="_blank">
							<i class="fab fa-facebook"></i>
						</a>
					</li>
				</ul>
			</div>
		</div>

	</div>
</footer>

app/views/layouts/_guest.html.erb
<div class="slice slice-lg bg-primary">
    <span class="tongue tongue-top tongue-secondary"><i class="fas fa-angle-up"></i></span>
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-12 text-center">
                <h3 class="font-weight-400 text-white">Vous souhaitez nous <span class="font-weight-700">rejoindre?</span>.</h3>
                <div class="mt-5">
                    <a href="<%= new_student_registration_path %>" class="btn btn-white btn-circle btn-translate--hover px-4">Inscription élève</a>
                    <a href="<%= new_teacher_registration_path %>" class="btn btn-white btn-circle btn-translate--hover px-4">Inscription professeur</a>
                    <a href="<%= new_establishment_registration_path %>" class="btn btn-white btn-circle btn-translate--hover px-4">Inscription établissement</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_logged.html.erb
<div class="slice slice-lg bg-primary">
    <span class="tongue tongue-top tongue-secondary"><i class="fas fa-angle-up"></i></span>
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-12 text-center">
                <h3 class="font-weight-400 text-white">Chercher un <span class="font-weight-700">professeur</span> ou
                    un <span class="font-weight-700">établissement</span> .</h3>
                <div class="mt-5">
                    <a href="<%= teachers_path %>" class="btn btn-white btn-circle btn-translate--hover px-4">Liste des
                        professeurs</a>
                    <a href="<%= establishments_path %>" class="btn btn-white btn-circle btn-translate--hover px-4">Liste
                        des établissements</a>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<header class="header-transparent">

    <!-- Main navbar -->

    <nav class="navbar navbar-main navbar-expand-lg navbar-sticky navbar-transparent navbar-light bg-white pt-2 pb-1"
        id="navbar-main">
        <div class="container">

            <!-- logo -->
            <a href="<%= root_path %>">
                <%= image_tag "AwaBookingWhite.png", alt: "logo", class: "btn-translate--hover w-50", id: "logo-nav" %>
                <%= image_tag "AwaBooking.png", alt: "logo-row", class: "btn-translate--hover w-25 pb-2", id: "logo-nav-row" %>
            </a>

            <!-- small navbar menu -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main-collapse"
                aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbar-main-collapse">
                <ul class="navbar-nav align-items-lg-center ml-lg-auto pt-1">

                    <!-- ............................USER IN.......................... -->
                    <% if user_signed_in? %>

                    <li class="nav-item dropdown dropdown-animate pr-5" data-toggle="hover">

                        <!-- icon -->
                        <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            <i class="fas fa-user-circle" style="font-size: 1.6em"></i>
                            <% if current_establishment %>
                                <%= current_user.name %>
                            <% elsif current_teacher %>
                                <%= current_user.first_name %> <%= current_user.last_name %>
                            <% elsif current_student %>
                                <%= current_user.first_name %> <%= current_user.last_name %>
                            <% end %>
                        </a>

                        <!-- dropdown menu -->
                        <div class="dropdown-menu dropdown-menu-md dropdown-menu-arrow">
                            <div class="list-group">

                                <a href="<%= get_dashboard(current_user) %>" class="list-group-item list-group-item-action">
                                    <div class="media d-flex align-items-center">
                                        <div class="media-body ml-3">
                                            <h6 class="mb-1">Dashboard</h6>
                                        </div>
                                    </div>
                                </a>
                                <a href="<%= get_profil(current_user) %>" class="list-group-item list-group-item-action">
                                    <div class="media d-flex align-items-center">
                                        <div class="media-body ml-3">
                                            <h6 class="mb-1">Profil</h6>
                                        </div>
                                    </div>
                                </a>
                                <a href="<%= get_logout %>" class="list-group-item list-group-item-action" data-method="DELETE">
                                    <div class="media d-flex align-items-center">
                                        <div class="media-body ml-3">
                                            <h6 class="mb-1"><strong>Déconnexion</strong></h6>
                                        </div>
                                    </div>
                                </a>

                            </div>
                        </div>

                    </li>


                    <!-- ............................USER OUT.......................... -->
                    <% else %>

                    <!-- LOG IN -->
                    <li class="nav-item dropdown dropdown-animate pr-3" data-toggle="hover">

                        <!-- button -->
                        <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">Se connecter</a>

                        <!-- dropdown menu -->
                        <div class="dropdown-menu dropdown-menu-md dropdown-menu-arrow">
                            <div class="list-group">

                                <a href="<%= new_student_session_path %>" class="list-group-item list-group-item-action">
                                    <div class="media d-flex align-items-center">
                                        <div class="media-body ml-1">
                                            <h6 class="mb-1"><i class="fas fa-circle btn-translate--hover mr-2 text-success"></i>&nbsp;Particulier</h6>
                                        </div>
                                    </div>
                                </a>
                                <a href="<%= new_teacher_session_path %>" class="list-group-item list-group-item-action">
                                    <div class="media d-flex align-items-center">
                                        <div class="media-body ml-1">
                                            <h6 class="mb-1"><i class="fas fa-circle btn-translate--hover mr-2 text-warning"></i>&nbsp;Professeur</h6>
                                        </div>
                                    </div>
                                </a>
                                <a href="<%= new_establishment_session_path %>" class="list-group-item list-group-item-action">
                                    <div class="media d-flex align-items-center">
                                        <div class="media-body ml-1">
                                            <h6 class="mb-1"><i class="fas fa-circle btn-translate--hover mr-2 text-danger"></i>&nbsp;Établissement</h6>
                                        </div>
                                    </div>
                                </a>

                            </div>
                        </div>

                    </li>

                    <!-- SIGN UP -->
                    <li class="nav-item dropdown dropdown-animate" data-toggle="hover">

                        <!-- button -->
                        <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">S'inscrire</a>

                        <!-- dropdown menu -->
                        <div class="dropdown-menu dropdown-menu-md dropdown-menu-arrow">
                            <div class="list-group">

                                <a href="<%= new_student_registration_path %>" class="list-group-item list-group-item-action">
                                    <div class="media d-flex align-items-center">
                                        <div class="media-body ml-1">
                                            <h6 class="mb-1"><i class="fas fa-circle btn-translate--hover mr-2 text-success"></i>&nbsp;Particulier</h6>
                                        </div>
                                    </div>
                                </a>
                                <a href="<%= new_teacher_registration_path %>" class="list-group-item list-group-item-action">
                                    <div class="media d-flex align-items-center">
                                        <div class="media-body ml-1">
                                            <h6 class="mb-1"><i class="fas fa-circle btn-translate--hover mr-2 text-warning"></i>&nbsp;Professeur</h6>
                                        </div>
                                    </div>
                                </a>
                                <a href="<%= new_establishment_registration_path %>" class="list-group-item list-group-item-action">
                                    <div class="media d-flex align-items-center">
                                        <div class="media-body ml-1">
                                            <h6 class="mb-1"><i class="fas fa-circle btn-translate--hover mr-2 text-danger"></i>&nbsp;Établissement</h6>
                                        </div>
                                    </div>
                                </a>

                            </div>
                        </div>

                    </li>

                    <% end %>

                </ul>

            </div>
        </div>
    </nav>
</header>